
export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'ar';

export const translations = {
  en: {
    // Nav
    nav_dashboard: 'Dashboard',
    nav_jobs: 'Selected Jobs',
    nav_inbox: 'Inbox Scanner',
    nav_analytics: 'Analytics',
    nav_settings: 'Settings',
    nav_help: 'Help & Guide',
    nav_subscription: 'Upgrade Plan',
    
    // General
    reset_app: 'Sign Out',
    delete_account: 'Delete Account',
    add_job: 'Add Job',
    synced: 'Synced',
    language_selector: 'Language',
    
    // Auth
    auth_login_title: 'Welcome Back',
    auth_signup_title: 'Create Account',
    auth_email: 'Email Address',
    auth_password: 'Password',
    auth_confirm_password: 'Confirm Password',
    auth_pass_mismatch: 'Passwords do not match',
    auth_btn_login: 'Log In',
    auth_btn_signup: 'Create Account',
    auth_no_account: "Don't have an account?",
    auth_has_account: 'Already have an account?',
    auth_forgot: 'Forgot Password?',
    auth_secure: 'Data stored locally on device',
    auth_or: 'Or continue with',
    auth_google: 'Google',
    auth_microsoft: 'Microsoft',
    auth_apple: 'Apple',

    // Dashboard Stats
    stat_detected: 'Total Detected',
    stat_auto_applied: 'Auto Applied',
    stat_interviews: 'Interviews',
    stat_action_needed: 'Action Needed',
    stat_click_track: 'Click to Track',
    chart_velocity: 'Application Velocity',
    chart_live_data: 'Live Data (Last 7 Days)',
    
    // Settings
    settings_title: 'Account & Preferences',
    settings_desc: 'Manage your personal information and job search criteria.',
    pref_title: 'Job Preferences',
    lang_label: 'App Language',

    // Subscription
    sub_title: 'Subscription Plans',
    sub_desc: 'Invest in your career for the price of a coffee.',
    plan_free: 'Free',
    plan_pro: 'Professional',
    plan_free_desc: 'Basic tracking for manual job seekers.',
    plan_pro_desc: 'Full automation suite.',
    feature_manual: 'Manual Job Tracking',
    feature_ai: 'Resume & Letter Writing (Unlimited)',
    feature_scan: 'Auto-Inbox Scanner',
    feature_auto: 'One-Click Auto Apply',
    price_5: '$5',
    btn_current: 'Current Plan',
    btn_upgrade: 'Upgrade to Pro',
    checkout_title: 'Secure Checkout',
    checkout_success: 'Payment Successful! You are now a Pro member.',

    // Onboarding
    welcome_title: 'Welcome to JobFlow AI',
    step_1_title: 'Create Your Profile',
    full_name: 'Full Name',
    email_addr: 'Email Address',
    email_hint: 'This email will be locked to this device.',
    phone: 'Phone Number',
    next_step_2: 'Next: Job Preferences',
    
    step_2_title: 'What are you looking for?',
    target_roles: 'Target Job Titles (Comma separated)',
    target_loc: 'Target Locations',
    min_salary: 'Min Annual Salary',
    remote_only: 'Remote Only',
    back: 'Back',
    next_step_3: 'Next: Upload Resume',
    
    step_3_title: 'Master Resume',
    secure_workspace: 'We have automatically created a secure workspace for your data.',
    connected: 'Connected:',
    change_path: 'Change',
    check_resume: "Check for 'resume.txt' in Workspace",
    upload_manual: 'OR UPLOAD MANUALLY',
    paste_resume: 'Resume Content (Editable)',
    complete_setup: 'Complete Setup',
    finishing: 'Finishing...',
    click_upload: 'Click to upload .txt'
  },
  es: {
    nav_dashboard: 'Panel de Control',
    nav_jobs: 'Empleos',
    nav_inbox: 'Escáner de Email',
    nav_analytics: 'Analítica',
    nav_settings: 'Configuración',
    nav_help: 'Ayuda y Guía',
    nav_subscription: 'Mejorar Plan',
    
    reset_app: 'Cerrar Sesión',
    delete_account: 'Borrar Cuenta',
    add_job: 'Añadir Empleo',
    synced: 'Sincronizado',
    language_selector: 'Idioma',
    
    auth_login_title: 'Bienvenido de nuevo',
    auth_signup_title: 'Crear Cuenta',
    auth_email: 'Correo Electrónico',
    auth_password: 'Contraseña',
    auth_confirm_password: 'Confirmar Contraseña',
    auth_pass_mismatch: 'Las contraseñas no coinciden',
    auth_btn_login: 'Iniciar Sesión',
    auth_btn_signup: 'Crear Cuenta',
    auth_no_account: "¿No tienes cuenta?",
    auth_has_account: '¿Ya tienes cuenta?',
    auth_forgot: '¿Olvidaste contraseña?',
    auth_secure: 'Datos guardados localmente',
    auth_or: 'O continuar con',
    auth_google: 'Google',
    auth_microsoft: 'Microsoft',
    auth_apple: 'Apple',

    stat_detected: 'Total Detectado',
    stat_auto_applied: 'Aplicado Auto',
    stat_interviews: 'Entrevistas',
    stat_action_needed: 'Acción Requerida',
    stat_click_track: 'Clic para rastrear',
    chart_velocity: 'Velocidad de Aplicación',
    chart_live_data: 'Datos en vivo (7 días)',
    
    settings_title: 'Cuenta y Preferencias',
    settings_desc: 'Administra tu información personal y criterios de búsqueda.',
    pref_title: 'Preferencias de Empleo',
    lang_label: 'Idioma de la App',

    sub_title: 'Planes de Suscripción',
    sub_desc: 'Invierte en tu carrera por el precio de un café.',
    plan_free: 'Gratis',
    plan_pro: 'Profesional',
    plan_free_desc: 'Rastreo básico.',
    plan_pro_desc: 'Automatización total.',
    feature_manual: 'Rastreo Manual',
    feature_ai: 'Escritura de CV e IA (Ilimitado)',
    feature_scan: 'Escáner de Bandeja',
    feature_auto: 'Auto-aplicación en un clic',
    price_5: '$5',
    btn_current: 'Plan Actual',
    btn_upgrade: 'Mejorar a Pro',
    checkout_title: 'Pago Seguro',
    checkout_success: '¡Pago Exitoso! Ahora eres miembro Pro.',

    welcome_title: 'Bienvenido a JobFlow AI',
    step_1_title: 'Crea tu Perfil',
    full_name: 'Nombre Completo',
    email_addr: 'Dirección de Email',
    email_hint: 'Este email estará vinculado a este dispositivo.',
    phone: 'Número de Teléfono',
    next_step_2: 'Siguiente: Preferencias',
    
    step_2_title: '¿Qué estás buscando?',
    target_roles: 'Títulos de Trabajo (Separados por comas)',
    target_loc: 'Ubicaciones',
    min_salary: 'Salario Mínimo Anual',
    remote_only: 'Solo Remoto',
    back: 'Atrás',
    next_step_3: 'Siguiente: Subir Currículum',
    
    step_3_title: 'Currículum Maestro',
    secure_workspace: 'Hemos creado un espacio seguro para tus datos.',
    connected: 'Conectado:',
    change_path: 'Cambiar',
    check_resume: "Buscar 'resume.txt' en espacio",
    upload_manual: 'O SUBIR MANUALMENTE',
    paste_resume: 'Contenido del Currículum (Editable)',
    complete_setup: 'Completar Configuración',
    finishing: 'Finalizando...',
    click_upload: 'Clic para subir .txt'
  },
  fr: {
    nav_dashboard: 'Tableau de Bord',
    nav_jobs: 'Emplois',
    nav_inbox: 'Scanner de Boîte',
    nav_analytics: 'Analytique',
    nav_settings: 'Paramètres',
    nav_help: 'Aide & Guide',
    nav_subscription: 'Abonnement',
    
    reset_app: 'Déconnexion',
    delete_account: 'Supprimer le compte',
    add_job: 'Ajouter Job',
    synced: 'Synchronisé',
    language_selector: 'Langue',
    
    auth_login_title: 'Bienvenue',
    auth_signup_title: 'Créer un Compte',
    auth_email: 'Adresse Email',
    auth_password: 'Mot de passe',
    auth_confirm_password: 'Confirmer Mot de passe',
    auth_pass_mismatch: 'Les mots de passe ne correspondent pas',
    auth_btn_login: 'Connexion',
    auth_btn_signup: 'S\'inscrire',
    auth_no_account: "Pas de compte ?",
    auth_has_account: 'Déjà un compte ?',
    auth_forgot: 'Mot de passe oublié ?',
    auth_secure: 'Données stockées localement',
    auth_or: 'Ou continuer avec',
    auth_google: 'Google',
    auth_microsoft: 'Microsoft',
    auth_apple: 'Apple',

    stat_detected: 'Total Détecté',
    stat_auto_applied: 'Postulé Auto',
    stat_interviews: 'Entretiens',
    stat_action_needed: 'Action Requise',
    stat_click_track: 'Suivre',
    chart_velocity: 'Vitesse de Candidature',
    chart_live_data: 'Données en direct (7j)',
    
    settings_title: 'Compte et Préférences',
    settings_desc: 'Gérez vos informations personnelles et critères de recherche.',
    pref_title: 'Préférences d\'Emploi',
    lang_label: 'Langue de l\'App',

    sub_title: 'Abonnements',
    sub_desc: 'Investissez dans votre carrière.',
    plan_free: 'Gratuit',
    plan_pro: 'Professionnel',
    plan_free_desc: 'Suivi basique.',
    plan_pro_desc: 'Automatisation complète.',
    feature_manual: 'Suivi manuel',
    feature_ai: 'Réécriture CV & Lettre (Illimité)',
    feature_scan: 'Scanner Auto',
    feature_auto: 'Candidature en un clic',
    price_5: '5€',
    btn_current: 'Plan Actuel',
    btn_upgrade: 'Passer Pro',
    checkout_title: 'Paiement Sécurisé',
    checkout_success: 'Paiement réussi ! Vous êtes Pro.',

    welcome_title: 'Bienvenue sur JobFlow AI',
    step_1_title: 'Créer votre profil',
    full_name: 'Nom Complet',
    email_addr: 'Adresse Email',
    email_hint: 'Cet email sera lié à cet appareil.',
    phone: 'Numéro de Téléphone',
    next_step_2: 'Suivant : Préférences',
    
    step_2_title: 'Que recherchez-vous ?',
    target_roles: 'Postes Ciblés (Séparés par virgule)',
    target_loc: 'Lieux Ciblés',
    min_salary: 'Salaire Min Annuel',
    remote_only: 'Télétravail Uniquement',
    back: 'Retour',
    next_step_3: 'Suivant : CV',
    
    step_3_title: 'CV Principal',
    secure_workspace: 'Espace de travail sécurisé créé automatiquement.',
    connected: 'Connecté :',
    change_path: 'Modifier',
    check_resume: "Vérifier 'resume.txt'",
    upload_manual: 'OU TÉLÉCHARGER MANUELLEMENT',
    paste_resume: 'Contenu du CV (Modifiable)',
    complete_setup: 'Terminer',
    finishing: 'Finalisation...',
    click_upload: 'Cliquez pour uploader .txt'
  },
  de: {
    nav_dashboard: 'Armaturenbrett',
    nav_jobs: 'Ausgewählte Jobs',
    nav_inbox: 'Posteingang',
    nav_analytics: 'Analytik',
    nav_settings: 'Einstellungen',
    nav_help: 'Hilfe & Anleitung',
    nav_subscription: 'Abo-Upgrade',
    
    reset_app: 'Abmelden',
    delete_account: 'Konto löschen',
    add_job: 'Job Hinzufügen',
    synced: 'Synchronisiert',
    language_selector: 'Sprache',
    
    auth_login_title: 'Willkommen zurück',
    auth_signup_title: 'Konto erstellen',
    auth_email: 'E-Mail-Adresse',
    auth_password: 'Passwort',
    auth_confirm_password: 'Passwort bestätigen',
    auth_pass_mismatch: 'Passwörter stimmen nicht überein',
    auth_btn_login: 'Anmelden',
    auth_btn_signup: 'Registrieren',
    auth_no_account: "Kein Konto?",
    auth_has_account: 'Bereits ein Konto?',
    auth_forgot: 'Passwort vergessen?',
    auth_secure: 'Daten lokal gespeichert',
    auth_or: 'Oder weiter mit',
    auth_google: 'Google',
    auth_microsoft: 'Microsoft',
    auth_apple: 'Apple',

    stat_detected: 'Erkannt Gesamt',
    stat_auto_applied: 'Auto-Bewerbung',
    stat_interviews: 'Interviews',
    stat_action_needed: 'Handlung Nötig',
    stat_click_track: 'Zum Verfolgen',
    chart_velocity: 'Bewerbungsgeschwindigkeit',
    chart_live_data: 'Live-Daten (Letzte 7 Tage)',
    
    settings_title: 'Konto & Einstellungen',
    settings_desc: 'Verwalten Sie Ihre persönlichen Daten und Suchkriterien.',
    pref_title: 'Job-Präferenzen',
    lang_label: 'App-Sprache',

    sub_title: 'Abonnements',
    sub_desc: 'Investieren Sie in Ihre Karriere.',
    plan_free: 'Kostenlos',
    plan_pro: 'Profi',
    plan_free_desc: 'Einfache Nachverfolgung.',
    plan_pro_desc: 'Volle Automatisierung.',
    feature_manual: 'Manuelle Nachverfolgung',
    feature_ai: 'KI-Lebenslauf & Briefe (Unbegrenzt)',
    feature_scan: 'Auto-Scanner',
    feature_auto: 'Ein-Klick-Bewerbung',
    price_5: '5€',
    btn_current: 'Aktueller Plan',
    btn_upgrade: 'Auf Pro upgraden',
    checkout_title: 'Sichere Kasse',
    checkout_success: 'Zahlung erfolgreich! Sie sind jetzt Pro.',

    welcome_title: 'Willkommen bei JobFlow AI',
    step_1_title: 'Profil erstellen',
    full_name: 'Vollständiger Name',
    email_addr: 'E-Mail-Adresse',
    email_hint: 'Diese E-Mail wird an dieses Gerät gebunden.',
    phone: 'Telefonnummer',
    next_step_2: 'Weiter: Präferenzen',
    
    step_2_title: 'Was suchen Sie?',
    target_roles: 'Zielpositionen (Kommagetrennt)',
    target_loc: 'Zielorte',
    min_salary: 'Mindestjahresgehalt',
    remote_only: 'Nur Remote',
    back: 'Zurück',
    next_step_3: 'Weiter: Lebenslauf',
    
    step_3_title: 'Hauptlebenslauf',
    secure_workspace: 'Sicherer Arbeitsbereich automatisch erstellt.',
    connected: 'Verbunden:',
    change_path: 'Ändern',
    check_resume: "'resume.txt' prüfen",
    upload_manual: 'ODER MANUELL HOCHLADEN',
    paste_resume: 'Lebenslauf-Inhalt (Bearbeitbar)',
    complete_setup: 'Einrichtung Abschließen',
    finishing: 'Fertigstellen...',
    click_upload: 'Klicken zum Hochladen (.txt)'
  },
  ar: {
    // Nav
    nav_dashboard: 'لوحة القيادة',
    nav_jobs: 'الوظائف المختارة',
    nav_inbox: 'فاحص البريد',
    nav_analytics: 'التحليلات',
    nav_settings: 'الإعدادات',
    nav_help: 'المساعدة',
    nav_subscription: 'ترقية الخطة',
    
    // General
    reset_app: 'تسجيل الخروج',
    delete_account: 'حذف الحساب',
    add_job: 'أضف وظيفة',
    synced: 'متزامن',
    language_selector: 'اللغة',

    // Auth
    auth_login_title: 'مرحبًا بعودتك',
    auth_signup_title: 'إنشاء حساب',
    auth_email: 'البريد الإلكتروني',
    auth_password: 'كلمة المرور',
    auth_confirm_password: 'تأكيد كلمة المرور',
    auth_pass_mismatch: 'كلمات المرور غير متطابقة',
    auth_btn_login: 'تسجيل الدخول',
    auth_btn_signup: 'إنشاء حساب',
    auth_no_account: "ليس لديك حساب؟",
    auth_has_account: 'لديك حساب بالفعل؟',
    auth_forgot: 'نسيت كلمة المرور؟',
    auth_secure: 'البيانات مخزنة محلياً',
    auth_or: 'أو الاستمرار مع',
    auth_google: 'جوجل',
    auth_microsoft: 'مايكروسوفت',
    auth_apple: 'أبل',
    
    // Dashboard Stats
    stat_detected: 'تم الكشف عنها',
    stat_auto_applied: 'تم التقديم آلياً',
    stat_interviews: 'مقابلات',
    stat_action_needed: 'إجراء مطلوب',
    stat_click_track: 'انقر للتتبع',
    chart_velocity: 'سرعة التقديم',
    chart_live_data: 'بيانات حية (آخر 7 أيام)',
    
    // Settings
    settings_title: 'الحساب والتفضيلات',
    settings_desc: 'إدارة معلوماتك الشخصية ومعايير البحث عن عمل.',
    pref_title: 'تفضيلات الوظيفة',
    lang_label: 'لغة التطبيق',

    sub_title: 'خطط الاشتراك',
    sub_desc: 'استثمر في مستقبلك المهني.',
    plan_free: 'مجاني',
    plan_pro: 'احترافي',
    plan_free_desc: 'تتبع يدوي أساسي.',
    plan_pro_desc: 'أتمتة كاملة.',
    feature_manual: 'تتبع يدوي للوظائف',
    feature_ai: 'كتابة سيرة ذاتية ورسائل (غير محدود)',
    feature_scan: 'ماسح البريد التلقائي',
    feature_auto: 'تقديم تلقائي بنقرة واحدة',
    price_5: '$5',
    btn_current: 'الخطة الحالية',
    btn_upgrade: 'الترقية إلى Pro',
    checkout_title: 'دفع آمن',
    checkout_success: 'تم الدفع بنجاح! أنت الآن عضو محترف.',

    // Onboarding
    welcome_title: 'مرحبًا بك في JobFlow AI',
    step_1_title: 'إنشاء ملفك الشخصي',
    full_name: 'الاسم الكامل',
    email_addr: 'عنوان البريد الإلكتروني',
    email_hint: 'سيتم ربط هذا البريد الإلكتروني بهذا الجهاز.',
    phone: 'رقم الهاتف',
    next_step_2: 'التالي: تفضيلات الوظيفة',
    
    step_2_title: 'ما الذي تبحث عنه؟',
    target_roles: 'المسميات الوظيفية (مفصولة بفواصل)',
    target_loc: 'المواقع المستهدفة',
    min_salary: 'الحد الأدنى للراتب السنوي',
    remote_only: 'عن بعد فقط',
    back: 'رجوع',
    next_step_3: 'التالي: رفع السيرة الذاتية',
    
    step_3_title: 'السيرة الذاتية الرئيسية',
    secure_workspace: 'لقد قمنا بإنشاء مساحة عمل آمنة لبياناتك تلقائيًا.',
    connected: 'متصل:',
    change_path: 'تغيير',
    check_resume: "تحقق من وجود 'resume.txt'",
    upload_manual: 'أو التحميل يدوياً',
    paste_resume: 'محتوى السيرة الذاتية (قابل للتعديل)',
    complete_setup: 'إكمال الإعداد',
    finishing: 'جاري الانتهاء...',
    click_upload: 'انقر لتحميل ملف .txt'
  }
};
